server:
  port: 8090
spring:
  cloud:
    gateway:
      routes:
        - id: weight_high
          uri: http://localhost:8081
          predicates:
            - Path=/name/**
dubbo:
  application:
    name: dubbo-springboot-demo-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848

