server:
  port: 8090
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: weight_high
#          uri: http://localhost:8081
#          predicates:
#            - Path=/name/**
spring:
  redis:
    port: 6379
    host: 127.0.0.1
    database: 3
dubbo:
  application:
    name: dubbo-springboot-gateway
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848

